// <auto-generated />
using FlasherData.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlasherData.Migrations
{
    [DbContext(typeof(FlasherContext))]
    [Migration("20211208233511_AddData")]
    partial class AddData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("FlasherData.DataModels.CategoryDm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectDmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SubjectId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectDmId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SubjectDmId = 1,
                            Title = "Category1"
                        },
                        new
                        {
                            Id = 2,
                            SubjectDmId = 1,
                            Title = "Category2"
                        },
                        new
                        {
                            Id = 3,
                            SubjectDmId = 1,
                            Title = "Category3"
                        },
                        new
                        {
                            Id = 4,
                            SubjectDmId = 1,
                            Title = "Category4"
                        },
                        new
                        {
                            Id = 5,
                            SubjectDmId = 2,
                            Title = "Category5"
                        },
                        new
                        {
                            Id = 6,
                            SubjectDmId = 2,
                            Title = "Category6"
                        },
                        new
                        {
                            Id = 7,
                            SubjectDmId = 2,
                            Title = "Category7"
                        },
                        new
                        {
                            Id = 8,
                            SubjectDmId = 2,
                            Title = "Category8"
                        });
                });

            modelBuilder.Entity("FlasherData.DataModels.FlashcardDm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnsweredCorrectly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryDmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CategoryId");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryDmId");

                    b.ToTable("Flashcards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnsweredCorrectly = false,
                            Back = "Back1",
                            CategoryDmId = 1,
                            Front = "Front1",
                            Title = "Flashcard1"
                        },
                        new
                        {
                            Id = 2,
                            AnsweredCorrectly = false,
                            Back = "Back2",
                            CategoryDmId = 1,
                            Front = "Front2",
                            Title = "Flashcard2"
                        },
                        new
                        {
                            Id = 3,
                            AnsweredCorrectly = false,
                            Back = "Back3",
                            CategoryDmId = 2,
                            Front = "Front3",
                            Title = "Flashcard3"
                        },
                        new
                        {
                            Id = 4,
                            AnsweredCorrectly = false,
                            Back = "Back4",
                            CategoryDmId = 2,
                            Front = "Front4",
                            Title = "Flashcard4"
                        },
                        new
                        {
                            Id = 5,
                            AnsweredCorrectly = false,
                            Back = "Back5",
                            CategoryDmId = 3,
                            Front = "Front5",
                            Title = "Flashcard5"
                        },
                        new
                        {
                            Id = 6,
                            AnsweredCorrectly = false,
                            Back = "Back6",
                            CategoryDmId = 3,
                            Front = "Front5",
                            Title = "Flashcard6"
                        },
                        new
                        {
                            Id = 7,
                            AnsweredCorrectly = false,
                            Back = "Back7",
                            CategoryDmId = 4,
                            Front = "Front7",
                            Title = "Flashcard7"
                        },
                        new
                        {
                            Id = 8,
                            AnsweredCorrectly = false,
                            Back = "Back8",
                            CategoryDmId = 4,
                            Front = "Front8",
                            Title = "Flashcard8"
                        });
                });

            modelBuilder.Entity("FlasherData.DataModels.SubjectDm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Subject1"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Subject2"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Subject3"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Subject4"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Subject5"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Subject6"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Subject7"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Subject8"
                        });
                });

            modelBuilder.Entity("FlasherData.DataModels.CategoryDm", b =>
                {
                    b.HasOne("FlasherData.DataModels.SubjectDm", null)
                        .WithMany("CategoriesDm")
                        .HasForeignKey("SubjectDmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlasherData.DataModels.FlashcardDm", b =>
                {
                    b.HasOne("FlasherData.DataModels.CategoryDm", null)
                        .WithMany("FlashcardsDm")
                        .HasForeignKey("CategoryDmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlasherData.DataModels.CategoryDm", b =>
                {
                    b.Navigation("FlashcardsDm");
                });

            modelBuilder.Entity("FlasherData.DataModels.SubjectDm", b =>
                {
                    b.Navigation("CategoriesDm");
                });
#pragma warning restore 612, 618
        }
    }
}
