// <auto-generated />
using FlasherData.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlasherData.Migrations
{
    [DbContext(typeof(FlasherContext))]
    [Migration("20211208232419_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("FlasherData.DataModels.CategoryDm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectDmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SubjectId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectDmId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FlasherData.DataModels.FlashcardDm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnsweredCorrectly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryDmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CategoryId");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryDmId");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("FlasherData.DataModels.SubjectDm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Subject1"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Subject2"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Subject3"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Subject4"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Subject5"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Subject6"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Subject7"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Subject8"
                        });
                });

            modelBuilder.Entity("FlasherData.DataModels.CategoryDm", b =>
                {
                    b.HasOne("FlasherData.DataModels.SubjectDm", null)
                        .WithMany("CategoriesDm")
                        .HasForeignKey("SubjectDmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlasherData.DataModels.FlashcardDm", b =>
                {
                    b.HasOne("FlasherData.DataModels.CategoryDm", null)
                        .WithMany("FlashcardsDm")
                        .HasForeignKey("CategoryDmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlasherData.DataModels.CategoryDm", b =>
                {
                    b.Navigation("FlashcardsDm");
                });

            modelBuilder.Entity("FlasherData.DataModels.SubjectDm", b =>
                {
                    b.Navigation("CategoriesDm");
                });
#pragma warning restore 612, 618
        }
    }
}
