// <auto-generated />
using FlasherData.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlasherData.Migrations
{
    [DbContext(typeof(FlasherContext))]
    [Migration("20220105185933_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("FlasherData.DataModels.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Category_1",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Category_2",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Category_3",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Category_4",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Category_5",
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Category_6",
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Category_7",
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Category_8",
                            SubjectId = 2
                        });
                });

            modelBuilder.Entity("FlasherData.DataModels.Flashcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnsweredCorrectly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Flashcards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnsweredCorrectly = false,
                            Back = "Back_1",
                            CategoryId = 1,
                            Front = "Front_1",
                            Name = "Flashcard_1"
                        },
                        new
                        {
                            Id = 2,
                            AnsweredCorrectly = false,
                            Back = "Back_2",
                            CategoryId = 1,
                            Front = "Front_2",
                            Name = "Flashcard_2"
                        },
                        new
                        {
                            Id = 3,
                            AnsweredCorrectly = false,
                            Back = "Back_3",
                            CategoryId = 2,
                            Front = "Front_3",
                            Name = "Flashcard_3"
                        },
                        new
                        {
                            Id = 4,
                            AnsweredCorrectly = false,
                            Back = "Back_4",
                            CategoryId = 2,
                            Front = "Front_4",
                            Name = "Flashcard_4"
                        },
                        new
                        {
                            Id = 5,
                            AnsweredCorrectly = false,
                            Back = "Back_5",
                            CategoryId = 3,
                            Front = "Front_5",
                            Name = "Flashcard_5"
                        },
                        new
                        {
                            Id = 6,
                            AnsweredCorrectly = false,
                            Back = "Back_6",
                            CategoryId = 3,
                            Front = "Front_5",
                            Name = "Flashcard_6"
                        },
                        new
                        {
                            Id = 7,
                            AnsweredCorrectly = false,
                            Back = "Back_7",
                            CategoryId = 4,
                            Front = "Front_7",
                            Name = "Flashcard_7"
                        },
                        new
                        {
                            Id = 8,
                            AnsweredCorrectly = false,
                            Back = "Back_8",
                            CategoryId = 4,
                            Front = "Front_8",
                            Name = "Flashcard_8"
                        });
                });

            modelBuilder.Entity("FlasherData.DataModels.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnsweredCorrectly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlashcardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnsweredCorrectly = false,
                            FlashcardId = 1,
                            Number = 1,
                            TestId = 1
                        },
                        new
                        {
                            Id = 2,
                            AnsweredCorrectly = false,
                            FlashcardId = 2,
                            Number = 2,
                            TestId = 2
                        },
                        new
                        {
                            Id = 3,
                            AnsweredCorrectly = false,
                            FlashcardId = 3,
                            Number = 3,
                            TestId = 3
                        },
                        new
                        {
                            Id = 4,
                            AnsweredCorrectly = false,
                            FlashcardId = 4,
                            Number = 4,
                            TestId = 4
                        });
                });

            modelBuilder.Entity("FlasherData.DataModels.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Subject_1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Subject_2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Subject_3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Subject_4"
                        });
                });

            modelBuilder.Entity("FlasherData.DataModels.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Test_1",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Test_2",
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Test_3",
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Test_4",
                            SubjectId = 4
                        });
                });

            modelBuilder.Entity("FlasherData.DataModels.Category", b =>
                {
                    b.HasOne("FlasherData.DataModels.Subject", null)
                        .WithMany("Categories")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlasherData.DataModels.Flashcard", b =>
                {
                    b.HasOne("FlasherData.DataModels.Category", null)
                        .WithMany("Flashcards")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlasherData.DataModels.Question", b =>
                {
                    b.HasOne("FlasherData.DataModels.Test", null)
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlasherData.DataModels.Test", b =>
                {
                    b.HasOne("FlasherData.DataModels.Subject", null)
                        .WithMany("Tests")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlasherData.DataModels.Category", b =>
                {
                    b.Navigation("Flashcards");
                });

            modelBuilder.Entity("FlasherData.DataModels.Subject", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("FlasherData.DataModels.Test", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
