// <auto-generated />
using System;
using Flasher.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlasherApi.Migrations
{
    [DbContext(typeof(FlasherContext))]
    [Migration("20211014184436_UpdatedFlashCardSetModel")]
    partial class UpdatedFlashCardSetModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("FlasherApi.Data.Models.FlashCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnsweredCorrectly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FlashCardSetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlashCardSetId");

                    b.ToTable("FlashCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnsweredCorrectly = false,
                            Back = "Back_1",
                            Front = "Front_1",
                            Title = "Title1"
                        },
                        new
                        {
                            Id = 2,
                            AnsweredCorrectly = false,
                            Back = "Back_2",
                            Front = "Front_2",
                            Title = "Title2"
                        },
                        new
                        {
                            Id = 3,
                            AnsweredCorrectly = false,
                            Back = "Back_3",
                            Front = "Front_3",
                            Title = "Title3"
                        },
                        new
                        {
                            Id = 4,
                            AnsweredCorrectly = false,
                            Back = "Back_4",
                            Front = "Front_4",
                            Title = "Title4"
                        });
                });

            modelBuilder.Entity("FlasherApi.Data.Models.FlashCardSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlashCardSupersetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlashCardSupersetId");

                    b.ToTable("FlashCardSet");
                });

            modelBuilder.Entity("FlasherApi.Data.Models.FlashCard", b =>
                {
                    b.HasOne("FlasherApi.Data.Models.FlashCardSet", "FlashCardSet")
                        .WithMany()
                        .HasForeignKey("FlashCardSetId");

                    b.Navigation("FlashCardSet");
                });

            modelBuilder.Entity("FlasherApi.Data.Models.FlashCardSet", b =>
                {
                    b.HasOne("FlasherApi.Data.Models.FlashCardSet", "FlashCardSuperset")
                        .WithMany()
                        .HasForeignKey("FlashCardSupersetId");

                    b.Navigation("FlashCardSuperset");
                });
#pragma warning restore 612, 618
        }
    }
}
